modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"


[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://www.anvilcraft.dev/#/additional/skyland"
logoFile = "assets/skyland/icon.png"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[mixins]]
config = "${mod_id}.mixins.json"

[modproperties."${mod_id}".anvillib.integrations]
rolling_gate = ["dev.anvilcraft.skyland.integration.rg.RollingGateIntegration"]
anvilcraft = ["dev.anvilcraft.skyland.integration.anvilcraft.AnvilCraftIntegration"]

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
